### ISSUE TITLE
Tamaño del cuadrilátero

### ISSUE THREAD

**Issue by DenJohX** [arduinoguate/OpenRobotChampionship#2]
Según las reglas está definido que es de 2mts, esto es muy poco, tomando en cuenta que ambos robots en conjunto ocupan un metro, ya casi no queda espacio para maniobrabilidad, y también reduce el area visible para los espectadores.

Como propuesta al menos 3, ideal 4 metros o mas, por supuesto también depende de dónde se vaya a realizar. 

Lo dejo para discusión.

**Comment by estuardomunoz** [comment]
Fijo 2 metros muy poco.... apoyo lo de 4..
Slds

**Comment by yeffrimic** [comment]
Bueno 4 metros entonces
