### ISSUE TITLE
tamaño del robot

### ISSUE THREAD

**Issue by DenJohX** [arduinoguate/OpenRobotChampionship#4]
"El robot deberá tener una máxima de 50 cm y una anchura de 50 cm."

No me queda claro si es de 50cm de todos lados, también de altura?

**Comment by yeffrimic** [comment]
Fijate que ni yo entendi esa parte jajajaj
Es de profundidad y anchura
Altura sin limites

**Comment by yeffrimic** [comment]
listo y paso a cerrar este issue  :)
